version: '3'
services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=docker_test
  app:
    image: docker-rest-test 
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mysql
    links:
      - mysql