version: '3'
services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=docker_test   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s 
    volumes:
    - db-data:/var/lib/mysql 
  app:
    image: docker-rest-test:1.0
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      mysql: 
        condition: service_healthy
    links:
      - mysql
volumes: 
  db-data:
    driver: local